// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: participant/v1/participant.proto

package participantv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Participant struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId          string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	IsAuthor         bool                   `protobuf:"varint,3,opt,name=is_author,json=isAuthor,proto3" json:"is_author,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DisplayName      *string                `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	TelegramUsername *string                `protobuf:"bytes,6,opt,name=telegram_username,json=telegramUsername,proto3,oneof" json:"telegram_username,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Participant) Reset() {
	*x = Participant{}
	mi := &file_participant_v1_participant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Participant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participant) ProtoMessage() {}

func (x *Participant) ProtoReflect() protoreflect.Message {
	mi := &file_participant_v1_participant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Participant.ProtoReflect.Descriptor instead.
func (*Participant) Descriptor() ([]byte, []int) {
	return file_participant_v1_participant_proto_rawDescGZIP(), []int{0}
}

func (x *Participant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Participant) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Participant) GetIsAuthor() bool {
	if x != nil {
		return x.IsAuthor
	}
	return false
}

func (x *Participant) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Participant) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *Participant) GetTelegramUsername() string {
	if x != nil && x.TelegramUsername != nil {
		return *x.TelegramUsername
	}
	return ""
}

type JoinEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareCode     string                 `protobuf:"bytes,1,opt,name=share_code,json=shareCode,proto3" json:"share_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinEventRequest) Reset() {
	*x = JoinEventRequest{}
	mi := &file_participant_v1_participant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinEventRequest) ProtoMessage() {}

func (x *JoinEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_participant_v1_participant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinEventRequest.ProtoReflect.Descriptor instead.
func (*JoinEventRequest) Descriptor() ([]byte, []int) {
	return file_participant_v1_participant_proto_rawDescGZIP(), []int{1}
}

func (x *JoinEventRequest) GetShareCode() string {
	if x != nil {
		return x.ShareCode
	}
	return ""
}

type JoinEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Participant   *Participant           `protobuf:"bytes,1,opt,name=participant,proto3" json:"participant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinEventResponse) Reset() {
	*x = JoinEventResponse{}
	mi := &file_participant_v1_participant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinEventResponse) ProtoMessage() {}

func (x *JoinEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_participant_v1_participant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinEventResponse.ProtoReflect.Descriptor instead.
func (*JoinEventResponse) Descriptor() ([]byte, []int) {
	return file_participant_v1_participant_proto_rawDescGZIP(), []int{2}
}

func (x *JoinEventResponse) GetParticipant() *Participant {
	if x != nil {
		return x.Participant
	}
	return nil
}

type ListParticipantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListParticipantsRequest) Reset() {
	*x = ListParticipantsRequest{}
	mi := &file_participant_v1_participant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListParticipantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParticipantsRequest) ProtoMessage() {}

func (x *ListParticipantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_participant_v1_participant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParticipantsRequest.ProtoReflect.Descriptor instead.
func (*ListParticipantsRequest) Descriptor() ([]byte, []int) {
	return file_participant_v1_participant_proto_rawDescGZIP(), []int{3}
}

func (x *ListParticipantsRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type ListParticipantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Participants  []*Participant         `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListParticipantsResponse) Reset() {
	*x = ListParticipantsResponse{}
	mi := &file_participant_v1_participant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListParticipantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParticipantsResponse) ProtoMessage() {}

func (x *ListParticipantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_participant_v1_participant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParticipantsResponse.ProtoReflect.Descriptor instead.
func (*ListParticipantsResponse) Descriptor() ([]byte, []int) {
	return file_participant_v1_participant_proto_rawDescGZIP(), []int{4}
}

func (x *ListParticipantsResponse) GetParticipants() []*Participant {
	if x != nil {
		return x.Participants
	}
	return nil
}

var File_participant_v1_participant_proto protoreflect.FileDescriptor

const file_participant_v1_participant_proto_rawDesc = "" +
	"\n" +
	" participant/v1/participant.proto\x12\x0eparticipant.v1\"\xf5\x01\n" +
	"\vParticipant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1b\n" +
	"\tis_author\x18\x03 \x01(\bR\bisAuthor\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12&\n" +
	"\fdisplay_name\x18\x05 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x120\n" +
	"\x11telegram_username\x18\x06 \x01(\tH\x01R\x10telegramUsername\x88\x01\x01B\x0f\n" +
	"\r_display_nameB\x14\n" +
	"\x12_telegram_username\"1\n" +
	"\x10JoinEventRequest\x12\x1d\n" +
	"\n" +
	"share_code\x18\x01 \x01(\tR\tshareCode\"R\n" +
	"\x11JoinEventResponse\x12=\n" +
	"\vparticipant\x18\x01 \x01(\v2\x1b.participant.v1.ParticipantR\vparticipant\"4\n" +
	"\x17ListParticipantsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"[\n" +
	"\x18ListParticipantsResponse\x12?\n" +
	"\fparticipants\x18\x01 \x03(\v2\x1b.participant.v1.ParticipantR\fparticipants2\xcd\x01\n" +
	"\x12ParticipantService\x12P\n" +
	"\tJoinEvent\x12 .participant.v1.JoinEventRequest\x1a!.participant.v1.JoinEventResponse\x12e\n" +
	"\x10ListParticipants\x12'.participant.v1.ListParticipantsRequest\x1a(.participant.v1.ListParticipantsResponseB\xac\x01\n" +
	"\x12com.participant.v1B\x10ParticipantProtoP\x01Z+SharedPrep/api/participant/v1;participantv1\xa2\x02\x03PXX\xaa\x02\x0eParticipant.V1\xca\x02\x0eParticipant\\V1\xe2\x02\x1aParticipant\\V1\\GPBMetadata\xea\x02\x0fParticipant::V1b\x06proto3"

var (
	file_participant_v1_participant_proto_rawDescOnce sync.Once
	file_participant_v1_participant_proto_rawDescData []byte
)

func file_participant_v1_participant_proto_rawDescGZIP() []byte {
	file_participant_v1_participant_proto_rawDescOnce.Do(func() {
		file_participant_v1_participant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_participant_v1_participant_proto_rawDesc), len(file_participant_v1_participant_proto_rawDesc)))
	})
	return file_participant_v1_participant_proto_rawDescData
}

var file_participant_v1_participant_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_participant_v1_participant_proto_goTypes = []any{
	(*Participant)(nil),              // 0: participant.v1.Participant
	(*JoinEventRequest)(nil),         // 1: participant.v1.JoinEventRequest
	(*JoinEventResponse)(nil),        // 2: participant.v1.JoinEventResponse
	(*ListParticipantsRequest)(nil),  // 3: participant.v1.ListParticipantsRequest
	(*ListParticipantsResponse)(nil), // 4: participant.v1.ListParticipantsResponse
}
var file_participant_v1_participant_proto_depIdxs = []int32{
	0, // 0: participant.v1.JoinEventResponse.participant:type_name -> participant.v1.Participant
	0, // 1: participant.v1.ListParticipantsResponse.participants:type_name -> participant.v1.Participant
	1, // 2: participant.v1.ParticipantService.JoinEvent:input_type -> participant.v1.JoinEventRequest
	3, // 3: participant.v1.ParticipantService.ListParticipants:input_type -> participant.v1.ListParticipantsRequest
	2, // 4: participant.v1.ParticipantService.JoinEvent:output_type -> participant.v1.JoinEventResponse
	4, // 5: participant.v1.ParticipantService.ListParticipants:output_type -> participant.v1.ListParticipantsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_participant_v1_participant_proto_init() }
func file_participant_v1_participant_proto_init() {
	if File_participant_v1_participant_proto != nil {
		return
	}
	file_participant_v1_participant_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_participant_v1_participant_proto_rawDesc), len(file_participant_v1_participant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_participant_v1_participant_proto_goTypes,
		DependencyIndexes: file_participant_v1_participant_proto_depIdxs,
		MessageInfos:      file_participant_v1_participant_proto_msgTypes,
	}.Build()
	File_participant_v1_participant_proto = out.File
	file_participant_v1_participant_proto_goTypes = nil
	file_participant_v1_participant_proto_depIdxs = nil
}
