// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: event/v1/event.proto

package eventv1connect

import (
	v1 "github.com/atcdot/SharedPrep/api/event/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EventServiceName is the fully-qualified name of the EventService service.
	EventServiceName = "event.v1.EventService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EventServiceCreateEventProcedure is the fully-qualified name of the EventService's CreateEvent
	// RPC.
	EventServiceCreateEventProcedure = "/event.v1.EventService/CreateEvent"
	// EventServiceGetEventProcedure is the fully-qualified name of the EventService's GetEvent RPC.
	EventServiceGetEventProcedure = "/event.v1.EventService/GetEvent"
	// EventServiceUpdateEventProcedure is the fully-qualified name of the EventService's UpdateEvent
	// RPC.
	EventServiceUpdateEventProcedure = "/event.v1.EventService/UpdateEvent"
	// EventServiceDeleteEventProcedure is the fully-qualified name of the EventService's DeleteEvent
	// RPC.
	EventServiceDeleteEventProcedure = "/event.v1.EventService/DeleteEvent"
	// EventServiceListMyEventsProcedure is the fully-qualified name of the EventService's ListMyEvents
	// RPC.
	EventServiceListMyEventsProcedure = "/event.v1.EventService/ListMyEvents"
)

// EventServiceClient is a client for the event.v1.EventService service.
type EventServiceClient interface {
	CreateEvent(context.Context, *connect.Request[v1.CreateEventRequest]) (*connect.Response[v1.CreateEventResponse], error)
	GetEvent(context.Context, *connect.Request[v1.GetEventRequest]) (*connect.Response[v1.GetEventResponse], error)
	UpdateEvent(context.Context, *connect.Request[v1.UpdateEventRequest]) (*connect.Response[v1.UpdateEventResponse], error)
	DeleteEvent(context.Context, *connect.Request[v1.DeleteEventRequest]) (*connect.Response[v1.DeleteEventResponse], error)
	ListMyEvents(context.Context, *connect.Request[v1.ListMyEventsRequest]) (*connect.Response[v1.ListMyEventsResponse], error)
}

// NewEventServiceClient constructs a client for the event.v1.EventService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEventServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EventServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	eventServiceMethods := v1.File_event_v1_event_proto.Services().ByName("EventService").Methods()
	return &eventServiceClient{
		createEvent: connect.NewClient[v1.CreateEventRequest, v1.CreateEventResponse](
			httpClient,
			baseURL+EventServiceCreateEventProcedure,
			connect.WithSchema(eventServiceMethods.ByName("CreateEvent")),
			connect.WithClientOptions(opts...),
		),
		getEvent: connect.NewClient[v1.GetEventRequest, v1.GetEventResponse](
			httpClient,
			baseURL+EventServiceGetEventProcedure,
			connect.WithSchema(eventServiceMethods.ByName("GetEvent")),
			connect.WithClientOptions(opts...),
		),
		updateEvent: connect.NewClient[v1.UpdateEventRequest, v1.UpdateEventResponse](
			httpClient,
			baseURL+EventServiceUpdateEventProcedure,
			connect.WithSchema(eventServiceMethods.ByName("UpdateEvent")),
			connect.WithClientOptions(opts...),
		),
		deleteEvent: connect.NewClient[v1.DeleteEventRequest, v1.DeleteEventResponse](
			httpClient,
			baseURL+EventServiceDeleteEventProcedure,
			connect.WithSchema(eventServiceMethods.ByName("DeleteEvent")),
			connect.WithClientOptions(opts...),
		),
		listMyEvents: connect.NewClient[v1.ListMyEventsRequest, v1.ListMyEventsResponse](
			httpClient,
			baseURL+EventServiceListMyEventsProcedure,
			connect.WithSchema(eventServiceMethods.ByName("ListMyEvents")),
			connect.WithClientOptions(opts...),
		),
	}
}

// eventServiceClient implements EventServiceClient.
type eventServiceClient struct {
	createEvent  *connect.Client[v1.CreateEventRequest, v1.CreateEventResponse]
	getEvent     *connect.Client[v1.GetEventRequest, v1.GetEventResponse]
	updateEvent  *connect.Client[v1.UpdateEventRequest, v1.UpdateEventResponse]
	deleteEvent  *connect.Client[v1.DeleteEventRequest, v1.DeleteEventResponse]
	listMyEvents *connect.Client[v1.ListMyEventsRequest, v1.ListMyEventsResponse]
}

// CreateEvent calls event.v1.EventService.CreateEvent.
func (c *eventServiceClient) CreateEvent(ctx context.Context, req *connect.Request[v1.CreateEventRequest]) (*connect.Response[v1.CreateEventResponse], error) {
	return c.createEvent.CallUnary(ctx, req)
}

// GetEvent calls event.v1.EventService.GetEvent.
func (c *eventServiceClient) GetEvent(ctx context.Context, req *connect.Request[v1.GetEventRequest]) (*connect.Response[v1.GetEventResponse], error) {
	return c.getEvent.CallUnary(ctx, req)
}

// UpdateEvent calls event.v1.EventService.UpdateEvent.
func (c *eventServiceClient) UpdateEvent(ctx context.Context, req *connect.Request[v1.UpdateEventRequest]) (*connect.Response[v1.UpdateEventResponse], error) {
	return c.updateEvent.CallUnary(ctx, req)
}

// DeleteEvent calls event.v1.EventService.DeleteEvent.
func (c *eventServiceClient) DeleteEvent(ctx context.Context, req *connect.Request[v1.DeleteEventRequest]) (*connect.Response[v1.DeleteEventResponse], error) {
	return c.deleteEvent.CallUnary(ctx, req)
}

// ListMyEvents calls event.v1.EventService.ListMyEvents.
func (c *eventServiceClient) ListMyEvents(ctx context.Context, req *connect.Request[v1.ListMyEventsRequest]) (*connect.Response[v1.ListMyEventsResponse], error) {
	return c.listMyEvents.CallUnary(ctx, req)
}

// EventServiceHandler is an implementation of the event.v1.EventService service.
type EventServiceHandler interface {
	CreateEvent(context.Context, *connect.Request[v1.CreateEventRequest]) (*connect.Response[v1.CreateEventResponse], error)
	GetEvent(context.Context, *connect.Request[v1.GetEventRequest]) (*connect.Response[v1.GetEventResponse], error)
	UpdateEvent(context.Context, *connect.Request[v1.UpdateEventRequest]) (*connect.Response[v1.UpdateEventResponse], error)
	DeleteEvent(context.Context, *connect.Request[v1.DeleteEventRequest]) (*connect.Response[v1.DeleteEventResponse], error)
	ListMyEvents(context.Context, *connect.Request[v1.ListMyEventsRequest]) (*connect.Response[v1.ListMyEventsResponse], error)
}

// NewEventServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEventServiceHandler(svc EventServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	eventServiceMethods := v1.File_event_v1_event_proto.Services().ByName("EventService").Methods()
	eventServiceCreateEventHandler := connect.NewUnaryHandler(
		EventServiceCreateEventProcedure,
		svc.CreateEvent,
		connect.WithSchema(eventServiceMethods.ByName("CreateEvent")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceGetEventHandler := connect.NewUnaryHandler(
		EventServiceGetEventProcedure,
		svc.GetEvent,
		connect.WithSchema(eventServiceMethods.ByName("GetEvent")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceUpdateEventHandler := connect.NewUnaryHandler(
		EventServiceUpdateEventProcedure,
		svc.UpdateEvent,
		connect.WithSchema(eventServiceMethods.ByName("UpdateEvent")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceDeleteEventHandler := connect.NewUnaryHandler(
		EventServiceDeleteEventProcedure,
		svc.DeleteEvent,
		connect.WithSchema(eventServiceMethods.ByName("DeleteEvent")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceListMyEventsHandler := connect.NewUnaryHandler(
		EventServiceListMyEventsProcedure,
		svc.ListMyEvents,
		connect.WithSchema(eventServiceMethods.ByName("ListMyEvents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/event.v1.EventService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EventServiceCreateEventProcedure:
			eventServiceCreateEventHandler.ServeHTTP(w, r)
		case EventServiceGetEventProcedure:
			eventServiceGetEventHandler.ServeHTTP(w, r)
		case EventServiceUpdateEventProcedure:
			eventServiceUpdateEventHandler.ServeHTTP(w, r)
		case EventServiceDeleteEventProcedure:
			eventServiceDeleteEventHandler.ServeHTTP(w, r)
		case EventServiceListMyEventsProcedure:
			eventServiceListMyEventsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEventServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEventServiceHandler struct{}

func (UnimplementedEventServiceHandler) CreateEvent(context.Context, *connect.Request[v1.CreateEventRequest]) (*connect.Response[v1.CreateEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("event.v1.EventService.CreateEvent is not implemented"))
}

func (UnimplementedEventServiceHandler) GetEvent(context.Context, *connect.Request[v1.GetEventRequest]) (*connect.Response[v1.GetEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("event.v1.EventService.GetEvent is not implemented"))
}

func (UnimplementedEventServiceHandler) UpdateEvent(context.Context, *connect.Request[v1.UpdateEventRequest]) (*connect.Response[v1.UpdateEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("event.v1.EventService.UpdateEvent is not implemented"))
}

func (UnimplementedEventServiceHandler) DeleteEvent(context.Context, *connect.Request[v1.DeleteEventRequest]) (*connect.Response[v1.DeleteEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("event.v1.EventService.DeleteEvent is not implemented"))
}

func (UnimplementedEventServiceHandler) ListMyEvents(context.Context, *connect.Request[v1.ListMyEventsRequest]) (*connect.Response[v1.ListMyEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("event.v1.EventService.ListMyEvents is not implemented"))
}
