// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: participant/v1/participant.proto

package participantv1connect

import (
	v1 "github.com/atcdot/SharedPrep/api/participant/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ParticipantServiceName is the fully-qualified name of the ParticipantService service.
	ParticipantServiceName = "participant.v1.ParticipantService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ParticipantServiceJoinEventProcedure is the fully-qualified name of the ParticipantService's
	// JoinEvent RPC.
	ParticipantServiceJoinEventProcedure = "/participant.v1.ParticipantService/JoinEvent"
	// ParticipantServiceListParticipantsProcedure is the fully-qualified name of the
	// ParticipantService's ListParticipants RPC.
	ParticipantServiceListParticipantsProcedure = "/participant.v1.ParticipantService/ListParticipants"
)

// ParticipantServiceClient is a client for the participant.v1.ParticipantService service.
type ParticipantServiceClient interface {
	JoinEvent(context.Context, *connect.Request[v1.JoinEventRequest]) (*connect.Response[v1.JoinEventResponse], error)
	ListParticipants(context.Context, *connect.Request[v1.ListParticipantsRequest]) (*connect.Response[v1.ListParticipantsResponse], error)
}

// NewParticipantServiceClient constructs a client for the participant.v1.ParticipantService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewParticipantServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ParticipantServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	participantServiceMethods := v1.File_participant_v1_participant_proto.Services().ByName("ParticipantService").Methods()
	return &participantServiceClient{
		joinEvent: connect.NewClient[v1.JoinEventRequest, v1.JoinEventResponse](
			httpClient,
			baseURL+ParticipantServiceJoinEventProcedure,
			connect.WithSchema(participantServiceMethods.ByName("JoinEvent")),
			connect.WithClientOptions(opts...),
		),
		listParticipants: connect.NewClient[v1.ListParticipantsRequest, v1.ListParticipantsResponse](
			httpClient,
			baseURL+ParticipantServiceListParticipantsProcedure,
			connect.WithSchema(participantServiceMethods.ByName("ListParticipants")),
			connect.WithClientOptions(opts...),
		),
	}
}

// participantServiceClient implements ParticipantServiceClient.
type participantServiceClient struct {
	joinEvent        *connect.Client[v1.JoinEventRequest, v1.JoinEventResponse]
	listParticipants *connect.Client[v1.ListParticipantsRequest, v1.ListParticipantsResponse]
}

// JoinEvent calls participant.v1.ParticipantService.JoinEvent.
func (c *participantServiceClient) JoinEvent(ctx context.Context, req *connect.Request[v1.JoinEventRequest]) (*connect.Response[v1.JoinEventResponse], error) {
	return c.joinEvent.CallUnary(ctx, req)
}

// ListParticipants calls participant.v1.ParticipantService.ListParticipants.
func (c *participantServiceClient) ListParticipants(ctx context.Context, req *connect.Request[v1.ListParticipantsRequest]) (*connect.Response[v1.ListParticipantsResponse], error) {
	return c.listParticipants.CallUnary(ctx, req)
}

// ParticipantServiceHandler is an implementation of the participant.v1.ParticipantService service.
type ParticipantServiceHandler interface {
	JoinEvent(context.Context, *connect.Request[v1.JoinEventRequest]) (*connect.Response[v1.JoinEventResponse], error)
	ListParticipants(context.Context, *connect.Request[v1.ListParticipantsRequest]) (*connect.Response[v1.ListParticipantsResponse], error)
}

// NewParticipantServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewParticipantServiceHandler(svc ParticipantServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	participantServiceMethods := v1.File_participant_v1_participant_proto.Services().ByName("ParticipantService").Methods()
	participantServiceJoinEventHandler := connect.NewUnaryHandler(
		ParticipantServiceJoinEventProcedure,
		svc.JoinEvent,
		connect.WithSchema(participantServiceMethods.ByName("JoinEvent")),
		connect.WithHandlerOptions(opts...),
	)
	participantServiceListParticipantsHandler := connect.NewUnaryHandler(
		ParticipantServiceListParticipantsProcedure,
		svc.ListParticipants,
		connect.WithSchema(participantServiceMethods.ByName("ListParticipants")),
		connect.WithHandlerOptions(opts...),
	)
	return "/participant.v1.ParticipantService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ParticipantServiceJoinEventProcedure:
			participantServiceJoinEventHandler.ServeHTTP(w, r)
		case ParticipantServiceListParticipantsProcedure:
			participantServiceListParticipantsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedParticipantServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedParticipantServiceHandler struct{}

func (UnimplementedParticipantServiceHandler) JoinEvent(context.Context, *connect.Request[v1.JoinEventRequest]) (*connect.Response[v1.JoinEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("participant.v1.ParticipantService.JoinEvent is not implemented"))
}

func (UnimplementedParticipantServiceHandler) ListParticipants(context.Context, *connect.Request[v1.ListParticipantsRequest]) (*connect.Response[v1.ListParticipantsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("participant.v1.ParticipantService.ListParticipants is not implemented"))
}
