// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: item/v1/item.proto

package itemv1connect

import (
	v1 "github.com/atcdot/SharedPrep/api/item/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ItemServiceName is the fully-qualified name of the ItemService service.
	ItemServiceName = "item.v1.ItemService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ItemServiceCreateItemProcedure is the fully-qualified name of the ItemService's CreateItem RPC.
	ItemServiceCreateItemProcedure = "/item.v1.ItemService/CreateItem"
	// ItemServiceUpdateItemProcedure is the fully-qualified name of the ItemService's UpdateItem RPC.
	ItemServiceUpdateItemProcedure = "/item.v1.ItemService/UpdateItem"
	// ItemServiceDeleteItemProcedure is the fully-qualified name of the ItemService's DeleteItem RPC.
	ItemServiceDeleteItemProcedure = "/item.v1.ItemService/DeleteItem"
	// ItemServiceClaimItemProcedure is the fully-qualified name of the ItemService's ClaimItem RPC.
	ItemServiceClaimItemProcedure = "/item.v1.ItemService/ClaimItem"
	// ItemServiceUnclaimItemProcedure is the fully-qualified name of the ItemService's UnclaimItem RPC.
	ItemServiceUnclaimItemProcedure = "/item.v1.ItemService/UnclaimItem"
	// ItemServiceAssignItemProcedure is the fully-qualified name of the ItemService's AssignItem RPC.
	ItemServiceAssignItemProcedure = "/item.v1.ItemService/AssignItem"
	// ItemServiceListItemsProcedure is the fully-qualified name of the ItemService's ListItems RPC.
	ItemServiceListItemsProcedure = "/item.v1.ItemService/ListItems"
)

// ItemServiceClient is a client for the item.v1.ItemService service.
type ItemServiceClient interface {
	CreateItem(context.Context, *connect.Request[v1.CreateItemRequest]) (*connect.Response[v1.CreateItemResponse], error)
	UpdateItem(context.Context, *connect.Request[v1.UpdateItemRequest]) (*connect.Response[v1.UpdateItemResponse], error)
	DeleteItem(context.Context, *connect.Request[v1.DeleteItemRequest]) (*connect.Response[v1.DeleteItemResponse], error)
	ClaimItem(context.Context, *connect.Request[v1.ClaimItemRequest]) (*connect.Response[v1.ClaimItemResponse], error)
	UnclaimItem(context.Context, *connect.Request[v1.UnclaimItemRequest]) (*connect.Response[v1.UnclaimItemResponse], error)
	AssignItem(context.Context, *connect.Request[v1.AssignItemRequest]) (*connect.Response[v1.AssignItemResponse], error)
	ListItems(context.Context, *connect.Request[v1.ListItemsRequest]) (*connect.Response[v1.ListItemsResponse], error)
}

// NewItemServiceClient constructs a client for the item.v1.ItemService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewItemServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ItemServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	itemServiceMethods := v1.File_item_v1_item_proto.Services().ByName("ItemService").Methods()
	return &itemServiceClient{
		createItem: connect.NewClient[v1.CreateItemRequest, v1.CreateItemResponse](
			httpClient,
			baseURL+ItemServiceCreateItemProcedure,
			connect.WithSchema(itemServiceMethods.ByName("CreateItem")),
			connect.WithClientOptions(opts...),
		),
		updateItem: connect.NewClient[v1.UpdateItemRequest, v1.UpdateItemResponse](
			httpClient,
			baseURL+ItemServiceUpdateItemProcedure,
			connect.WithSchema(itemServiceMethods.ByName("UpdateItem")),
			connect.WithClientOptions(opts...),
		),
		deleteItem: connect.NewClient[v1.DeleteItemRequest, v1.DeleteItemResponse](
			httpClient,
			baseURL+ItemServiceDeleteItemProcedure,
			connect.WithSchema(itemServiceMethods.ByName("DeleteItem")),
			connect.WithClientOptions(opts...),
		),
		claimItem: connect.NewClient[v1.ClaimItemRequest, v1.ClaimItemResponse](
			httpClient,
			baseURL+ItemServiceClaimItemProcedure,
			connect.WithSchema(itemServiceMethods.ByName("ClaimItem")),
			connect.WithClientOptions(opts...),
		),
		unclaimItem: connect.NewClient[v1.UnclaimItemRequest, v1.UnclaimItemResponse](
			httpClient,
			baseURL+ItemServiceUnclaimItemProcedure,
			connect.WithSchema(itemServiceMethods.ByName("UnclaimItem")),
			connect.WithClientOptions(opts...),
		),
		assignItem: connect.NewClient[v1.AssignItemRequest, v1.AssignItemResponse](
			httpClient,
			baseURL+ItemServiceAssignItemProcedure,
			connect.WithSchema(itemServiceMethods.ByName("AssignItem")),
			connect.WithClientOptions(opts...),
		),
		listItems: connect.NewClient[v1.ListItemsRequest, v1.ListItemsResponse](
			httpClient,
			baseURL+ItemServiceListItemsProcedure,
			connect.WithSchema(itemServiceMethods.ByName("ListItems")),
			connect.WithClientOptions(opts...),
		),
	}
}

// itemServiceClient implements ItemServiceClient.
type itemServiceClient struct {
	createItem  *connect.Client[v1.CreateItemRequest, v1.CreateItemResponse]
	updateItem  *connect.Client[v1.UpdateItemRequest, v1.UpdateItemResponse]
	deleteItem  *connect.Client[v1.DeleteItemRequest, v1.DeleteItemResponse]
	claimItem   *connect.Client[v1.ClaimItemRequest, v1.ClaimItemResponse]
	unclaimItem *connect.Client[v1.UnclaimItemRequest, v1.UnclaimItemResponse]
	assignItem  *connect.Client[v1.AssignItemRequest, v1.AssignItemResponse]
	listItems   *connect.Client[v1.ListItemsRequest, v1.ListItemsResponse]
}

// CreateItem calls item.v1.ItemService.CreateItem.
func (c *itemServiceClient) CreateItem(ctx context.Context, req *connect.Request[v1.CreateItemRequest]) (*connect.Response[v1.CreateItemResponse], error) {
	return c.createItem.CallUnary(ctx, req)
}

// UpdateItem calls item.v1.ItemService.UpdateItem.
func (c *itemServiceClient) UpdateItem(ctx context.Context, req *connect.Request[v1.UpdateItemRequest]) (*connect.Response[v1.UpdateItemResponse], error) {
	return c.updateItem.CallUnary(ctx, req)
}

// DeleteItem calls item.v1.ItemService.DeleteItem.
func (c *itemServiceClient) DeleteItem(ctx context.Context, req *connect.Request[v1.DeleteItemRequest]) (*connect.Response[v1.DeleteItemResponse], error) {
	return c.deleteItem.CallUnary(ctx, req)
}

// ClaimItem calls item.v1.ItemService.ClaimItem.
func (c *itemServiceClient) ClaimItem(ctx context.Context, req *connect.Request[v1.ClaimItemRequest]) (*connect.Response[v1.ClaimItemResponse], error) {
	return c.claimItem.CallUnary(ctx, req)
}

// UnclaimItem calls item.v1.ItemService.UnclaimItem.
func (c *itemServiceClient) UnclaimItem(ctx context.Context, req *connect.Request[v1.UnclaimItemRequest]) (*connect.Response[v1.UnclaimItemResponse], error) {
	return c.unclaimItem.CallUnary(ctx, req)
}

// AssignItem calls item.v1.ItemService.AssignItem.
func (c *itemServiceClient) AssignItem(ctx context.Context, req *connect.Request[v1.AssignItemRequest]) (*connect.Response[v1.AssignItemResponse], error) {
	return c.assignItem.CallUnary(ctx, req)
}

// ListItems calls item.v1.ItemService.ListItems.
func (c *itemServiceClient) ListItems(ctx context.Context, req *connect.Request[v1.ListItemsRequest]) (*connect.Response[v1.ListItemsResponse], error) {
	return c.listItems.CallUnary(ctx, req)
}

// ItemServiceHandler is an implementation of the item.v1.ItemService service.
type ItemServiceHandler interface {
	CreateItem(context.Context, *connect.Request[v1.CreateItemRequest]) (*connect.Response[v1.CreateItemResponse], error)
	UpdateItem(context.Context, *connect.Request[v1.UpdateItemRequest]) (*connect.Response[v1.UpdateItemResponse], error)
	DeleteItem(context.Context, *connect.Request[v1.DeleteItemRequest]) (*connect.Response[v1.DeleteItemResponse], error)
	ClaimItem(context.Context, *connect.Request[v1.ClaimItemRequest]) (*connect.Response[v1.ClaimItemResponse], error)
	UnclaimItem(context.Context, *connect.Request[v1.UnclaimItemRequest]) (*connect.Response[v1.UnclaimItemResponse], error)
	AssignItem(context.Context, *connect.Request[v1.AssignItemRequest]) (*connect.Response[v1.AssignItemResponse], error)
	ListItems(context.Context, *connect.Request[v1.ListItemsRequest]) (*connect.Response[v1.ListItemsResponse], error)
}

// NewItemServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewItemServiceHandler(svc ItemServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	itemServiceMethods := v1.File_item_v1_item_proto.Services().ByName("ItemService").Methods()
	itemServiceCreateItemHandler := connect.NewUnaryHandler(
		ItemServiceCreateItemProcedure,
		svc.CreateItem,
		connect.WithSchema(itemServiceMethods.ByName("CreateItem")),
		connect.WithHandlerOptions(opts...),
	)
	itemServiceUpdateItemHandler := connect.NewUnaryHandler(
		ItemServiceUpdateItemProcedure,
		svc.UpdateItem,
		connect.WithSchema(itemServiceMethods.ByName("UpdateItem")),
		connect.WithHandlerOptions(opts...),
	)
	itemServiceDeleteItemHandler := connect.NewUnaryHandler(
		ItemServiceDeleteItemProcedure,
		svc.DeleteItem,
		connect.WithSchema(itemServiceMethods.ByName("DeleteItem")),
		connect.WithHandlerOptions(opts...),
	)
	itemServiceClaimItemHandler := connect.NewUnaryHandler(
		ItemServiceClaimItemProcedure,
		svc.ClaimItem,
		connect.WithSchema(itemServiceMethods.ByName("ClaimItem")),
		connect.WithHandlerOptions(opts...),
	)
	itemServiceUnclaimItemHandler := connect.NewUnaryHandler(
		ItemServiceUnclaimItemProcedure,
		svc.UnclaimItem,
		connect.WithSchema(itemServiceMethods.ByName("UnclaimItem")),
		connect.WithHandlerOptions(opts...),
	)
	itemServiceAssignItemHandler := connect.NewUnaryHandler(
		ItemServiceAssignItemProcedure,
		svc.AssignItem,
		connect.WithSchema(itemServiceMethods.ByName("AssignItem")),
		connect.WithHandlerOptions(opts...),
	)
	itemServiceListItemsHandler := connect.NewUnaryHandler(
		ItemServiceListItemsProcedure,
		svc.ListItems,
		connect.WithSchema(itemServiceMethods.ByName("ListItems")),
		connect.WithHandlerOptions(opts...),
	)
	return "/item.v1.ItemService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ItemServiceCreateItemProcedure:
			itemServiceCreateItemHandler.ServeHTTP(w, r)
		case ItemServiceUpdateItemProcedure:
			itemServiceUpdateItemHandler.ServeHTTP(w, r)
		case ItemServiceDeleteItemProcedure:
			itemServiceDeleteItemHandler.ServeHTTP(w, r)
		case ItemServiceClaimItemProcedure:
			itemServiceClaimItemHandler.ServeHTTP(w, r)
		case ItemServiceUnclaimItemProcedure:
			itemServiceUnclaimItemHandler.ServeHTTP(w, r)
		case ItemServiceAssignItemProcedure:
			itemServiceAssignItemHandler.ServeHTTP(w, r)
		case ItemServiceListItemsProcedure:
			itemServiceListItemsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedItemServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedItemServiceHandler struct{}

func (UnimplementedItemServiceHandler) CreateItem(context.Context, *connect.Request[v1.CreateItemRequest]) (*connect.Response[v1.CreateItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("item.v1.ItemService.CreateItem is not implemented"))
}

func (UnimplementedItemServiceHandler) UpdateItem(context.Context, *connect.Request[v1.UpdateItemRequest]) (*connect.Response[v1.UpdateItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("item.v1.ItemService.UpdateItem is not implemented"))
}

func (UnimplementedItemServiceHandler) DeleteItem(context.Context, *connect.Request[v1.DeleteItemRequest]) (*connect.Response[v1.DeleteItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("item.v1.ItemService.DeleteItem is not implemented"))
}

func (UnimplementedItemServiceHandler) ClaimItem(context.Context, *connect.Request[v1.ClaimItemRequest]) (*connect.Response[v1.ClaimItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("item.v1.ItemService.ClaimItem is not implemented"))
}

func (UnimplementedItemServiceHandler) UnclaimItem(context.Context, *connect.Request[v1.UnclaimItemRequest]) (*connect.Response[v1.UnclaimItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("item.v1.ItemService.UnclaimItem is not implemented"))
}

func (UnimplementedItemServiceHandler) AssignItem(context.Context, *connect.Request[v1.AssignItemRequest]) (*connect.Response[v1.AssignItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("item.v1.ItemService.AssignItem is not implemented"))
}

func (UnimplementedItemServiceHandler) ListItems(context.Context, *connect.Request[v1.ListItemsRequest]) (*connect.Response[v1.ListItemsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("item.v1.ItemService.ListItems is not implemented"))
}
